Be more verbose when test setup fails

diff --git a/t/run b/t/run
--- a/t/run
+++ b/t/run
@@ -3,11 +3,11 @@
 # Tests should be run from the tests directory
 if ! test "$(basename "$PWD")" = "t"
 then
-	        cd t || exit 2
+	cd t || { >&2 printf "%s\n" "Cannot cd into test directory!"; exit 2; }
 fi
 
 # We need an executable
-test -x ../w3m || exit 2
+test -x ../w3m || { >&2 printf "%s\n" "No executable!";  exit 2; }
 
 test "$1" || set -- [0-9][0-9][0-9][0-9]*
 
